@echo off
chcp 65001 >nul

set "m3u=youtube_live.m3u"
del "%m3u%" 2>nul

echo #EXTM3U > "%m3u%"
echo # Generated by GitHub Actions - %DATE% %TIME% >> "%m3u%"
echo. >> "%m3u%"

echo ========================================
echo Starting to generate YouTube live m3u...
echo ========================================

for /f "usebackq tokens=1,2,3 delims=|" %%a in ("channels.txt") do (
    echo [+] Processing: %%a

    for /f "delims=" %%u in ('yt-dlp -g --no-playlist --flat-playlist "%%c/live" 2^>nul') do (
        if "%%u"=="" (
            echo [失敗] 無法獲取直播地址: %%c
        ) else (
            echo #EXTINF:-1 tvg-name="%%a" group-title="%%b",%%a >> "%m3u%"
            echo %%u >> "%m3u%"
            echo. >> "%m3u%"
            echo [成功] %%a
        )
    )
)

echo.
echo 完成！生成檔案：%m3u%
echo 行數：
find /c /v "" %m3u%