@echo off
chcp 65001 >nul

set "m3u=youtube_live.m3u"
del "%m3u%" 2>nul

echo #EXTM3U > "%m3u%"
echo # Generated by GitHub Actions DEBUG - %DATE% %TIME% >> "%m3u%"
echo. >> "%m3u%"

echo ==================================================
echo Starting debug generation of YouTube live m3u...
echo ==================================================

for /f "usebackq tokens=1,2,3 delims=|" %%a in ("channels.txt") do (
    echo.
    echo ==================================================
    echo Processing channel: %%a   (group: %%b)
    echo URL: %%c
    echo Command: yt-dlp -g --no-playlist --flat-playlist "%%c/live"
    
    echo Fetching live stream URL...
    for /f "delims=" %%u in ('yt-dlp -g --no-playlist --flat-playlist "%%c/live" 2^>^&1') do (
        echo yt-dlp output: %%u
    )
    
    set "URL="
    for /f "delims=" %%u in ('yt-dlp -g --no-playlist --flat-playlist "%%c/live" 2^>nul') do set "URL=%%u"
    
    if "!URL!"=="" (
        echo [失敗] 沒有取得直播網址
        echo 可能原因：該頻道未開播、連結無效、或被限制
    ) else (
        echo [成功] 取得直播網址: !URL!
        echo #EXTINF:-1 tvg-name="%%a" group-title="%%b",%%a >> "%m3u%"
        echo !URL! >> "%m3u%"
        echo. >> "%m3u%"
    )
)

echo.
echo ==================================================
echo 完成！最終生成檔案內容如下：
type "%m3u%"
echo ==================================================
